/********************************************************************
 * bg_CommunitiesSelfRegConfirmCtrl_Test
 *
 * Unit tests for bg_CommunitiesSelfRegConfirmCtrl_Test
 * 
 * Author: Chris Eales - BrightGen Ltd
 * Created: 30-01-2015
 * Changes: 
 *
 ********************************************************************/
@IsTest
private class bg_CommunitiesSelfRegConfirmCtrl_Test 
{
	static testMethod void testController()
	{
		bg_CommunitiesSelfRegConfirmController cntrl = new bg_CommunitiesSelfRegConfirmController();
	}
}