/********************************************************************
 * bg_CookiePageController 
 *
 * Controller class for bg_CookieWrapper
 * 
 * Test Class: Various
 *
 * Author: Chris Eales - BrightGen Ltd
 * Created: 24-03-2014
 * Changes: 
 * 
 ********************************************************************/
public class bg_CookieWrapper 
{
	public String CookieName {get; set;}
	public String Description {get; set;}
	public String Expires {get; set;}
	
}