/********************************************************************
 * bg_CommunitiesSelfRegConfirmController 
 *
 * Extenstion controller for Registration Confirmation Visualforce page
 * 
 * Test Class: bg_CommunitiesSelfRegConfirmCtrl_Test
 *
 * Author: Chris Eales - BrightGen Ltd
 * Created: 30-01-2015
 * Changes: 
 *
 ********************************************************************/
public with sharing class bg_CommunitiesSelfRegConfirmController 
{
	public bg_CommunitiesSelfRegConfirmController()
	{
		
	}
	
}